### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by DreadBoy** [joonatoona/OpenMineMods#2]
Steps to reproduce:

1. run GUI_Win.bat
2. visit http://127.0.0.1:7385/

Page shows 500 error with message

```
Error: 500 Internal Server Error
Sorry, the requested URL 'http://127.0.0.1:7385/' caused an error:
Template 'index' not found.

```
Stack trace:
```
Bottle v0.12.13 server starting up (using WSGIRefServer())...
Listening on http://127.0.0.1:7385/
Hit Ctrl-C to quit.

127.0.0.1 - - [12/Aug/2017 22:30:40] "GET / HTTP/1.1" 500 757
127.0.0.1 - - [12/Aug/2017 22:30:40] "GET /favicon.ico HTTP/1.1" 404 742
127.0.0.1 - - [12/Aug/2017 22:31:13] "GET / HTTP/1.1" 500 757
Traceback (most recent call last):
  File "I:\Users\Dread\Documents\GitHub\OpenMineMods\Installers\python\lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "I:\Users\Dread\Documents\GitHub\OpenMineMods\Installers\python\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "I:\Users\Dread\Documents\GitHub\OpenMineMods\Installers\python\lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "I:\Users\Dread\Documents\GitHub\OpenMineMods\Installers\python\lib\wsgiref\handlers.py", line 332, in send_headers
    self.send_preamble()
  File "I:\Users\Dread\Documents\GitHub\OpenMineMods\Installers\python\lib\wsgiref\handlers.py", line 255, in send_preamble
    ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
  File "I:\Users\Dread\Documents\GitHub\OpenMineMods\Installers\python\lib\wsgiref\handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "I:\Users\Dread\Documents\GitHub\OpenMineMods\Installers\python\lib\socketserver.py", line 775, in write
    self._sock.sendall(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
127.0.0.1 - - [12/Aug/2017 22:31:13] "GET / HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 52745)
Traceback (most recent call last):
  File "I:\Users\Dread\Documents\GitHub\OpenMineMods\Installers\python\lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "I:\Users\Dread\Documents\GitHub\OpenMineMods\Installers\python\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "I:\Users\Dread\Documents\GitHub\OpenMineMods\Installers\python\lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "I:\Users\Dread\Documents\GitHub\OpenMineMods\Installers\python\lib\wsgiref\handlers.py", line 332, in send_headers
    self.send_preamble()
  File "I:\Users\Dread\Documents\GitHub\OpenMineMods\Installers\python\lib\wsgiref\handlers.py", line 255, in send_preamble
    ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
  File "I:\Users\Dread\Documents\GitHub\OpenMineMods\Installers\python\lib\wsgiref\handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "I:\Users\Dread\Documents\GitHub\OpenMineMods\Installers\python\lib\socketserver.py", line 775, in write
    self._sock.sendall(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "I:\Users\Dread\Documents\GitHub\OpenMineMods\Installers\python\lib\wsgiref\handlers.py", line 141, in run
    self.handle_error()
  File "I:\Users\Dread\Documents\GitHub\OpenMineMods\Installers\python\lib\wsgiref\handlers.py", line 368, in handle_error
    self.finish_response()
  File "I:\Users\Dread\Documents\GitHub\OpenMineMods\Installers\python\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "I:\Users\Dread\Documents\GitHub\OpenMineMods\Installers\python\lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "I:\Users\Dread\Documents\GitHub\OpenMineMods\Installers\python\lib\wsgiref\handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "I:\Users\Dread\Documents\GitHub\OpenMineMods\Installers\python\lib\wsgiref\handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "I:\Users\Dread\Documents\GitHub\OpenMineMods\Installers\python\lib\socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "I:\Users\Dread\Documents\GitHub\OpenMineMods\Installers\python\lib\socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "I:\Users\Dread\Documents\GitHub\OpenMineMods\Installers\python\lib\socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "I:\Users\Dread\Documents\GitHub\OpenMineMods\Installers\python\lib\socketserver.py", line 696, in __init__
    self.handle()
  File "I:\Users\Dread\Documents\GitHub\OpenMineMods\Installers\python\lib\wsgiref\simple_server.py", line 133, in handle
    handler.run(self.server.get_app())
  File "I:\Users\Dread\Documents\GitHub\OpenMineMods\Installers\python\lib\wsgiref\handlers.py", line 144, in run
    self.close()
  File "I:\Users\Dread\Documents\GitHub\OpenMineMods\Installers\python\lib\wsgiref\simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
127.0.0.1 - - [12/Aug/2017 22:31:13] "GET / HTTP/1.1" 500 757
127.0.0.1 - - [12/Aug/2017 22:31:13] "GET /favicon.ico HTTP/1.1" 404 742
```

**Comment by notjuliee** [comment]
Try disabling the windows firewall temporarily?

**Comment by FnordMan** [comment]
I get the same issue here on windows (10 64-bit) and the firewall is disabled.

**Comment by notjuliee** [comment]
@FnordMan Interesting. I don't have a win10 VM to test on, so I can't be sure what the issue is.

Try the Qt UI instead?

**Comment by FnordMan** [comment]
May have been a bad download from last night? Manually installed python, shoved it in the system path and grabbed a new zip clone of the archive and everything looks like it works now.

**Comment by notjuliee** [comment]
@FnordMan I've never heard of something like that happening, but maybe.

The newest version uses Qt instead of a webui, and that seems to play nicer with windows.

**Comment by FnordMan** [comment]
oh hey... a GUI, here I just mindlessly started the WebUI file....

looks like the gui works fine, though catching the enter key on the "search mods" to initiate a search would be nice

**Comment by notjuliee** [comment]
I thought I deleted the WebUI file?

Yep, capturing the enter key is on my TODO for today.

Seems this issue is closed, becuase the WebUI is no longer in use. Awesome!

**Comment by notjuliee** [comment]
@FnordMan, added enter listener in 5245aa8, try that :D

**Comment by FnordMan** [comment]
Woo, that's works great, thanks.
