### ISSUE TITLE
ui-v2 does not start.

### ISSUE THREAD

**Issue by Maddremor** [joonatoona/OpenMineMods#23]
Problem: The `ui-v2` branch does not start up.

Procedure I use when attempting to launch OMMv2:
- Clone repo locally
- run `uibuild.sh`
- run command `python OpenMineMods.py` with cmd in OMMv2 base dir

Log below:
```
D:\Program Files (x86)\Minecraft\CustomSoftware\OpenMineMods_ui-v2>python OpenMineMods.py
[09/18/17 10:01:56][INFO] Starting OpenMineMods v1.1.0
[09/18/17 10:01:56][INFO] Data dir: F:/AppData/Roaming/python
Traceback (most recent call last):
  File "OpenMineMods.py", line 9, in <module>
    win = MainWindow()
  File "D:\Program Files (x86)\Minecraft\CustomSoftware\OpenMineMods_ui-v2\GUI\MainWindowWrapper.py", line 69, in __init__
    self.mmc = MultiMC(self.curse.baseDir)
  File "D:\Program Files (x86)\Minecraft\CustomSoftware\OpenMineMods_ui-v2\API\MultiMC.py", line 29, in __init__
    self.instances = [MultiMCInstance(i, self.metaDb) for i in cfgFiles]
  File "D:\Program Files (x86)\Minecraft\CustomSoftware\OpenMineMods_ui-v2\API\MultiMC.py", line 29, in <listcomp>
    self.instances = [MultiMCInstance(i, self.metaDb) for i in cfgFiles]
  File "D:\Program Files (x86)\Minecraft\CustomSoftware\OpenMineMods_ui-v2\API\MultiMC.py", line 134, in __init__
    self.file = self.db[self.uuid]["file"]
KeyError: 'file'
```

**Comment by notjuliee** [comment]
Did you delete all three files that start with `meta.db` from your MultiMC folder?

**Comment by Maddremor** [comment]
I did (again), and now it worked.

**Comment by notjuliee** [comment]
Awesome. Once 2.0 is released I will make sure backwards compatibility never breaks again.
