### ISSUE TITLE
[ui-v2] Crash on instance edit

### ISSUE THREAD

**Issue by Maddremor** [joonatoona/OpenMineMods#27]
Stacktrace:
```
D:\Program Files (x86)\Minecraft\CustomSoftware\OpenMineMods>python OpenMineMods.py
[09/24/17 16:30:49][INFO] Data dir: F:/AppData/Roaming/python
[09/24/17 16:30:49][INFO] Cache dir: C:/Users/Maddremor/AppData/Local/python/cache
['OpenMineMods.py']
Traceback (most recent call last):
  File "D:\Program Files (x86)\Minecraft\CustomSoftware\OpenMineMods\GUI\MainWindowWrapper.py", line 151, in edit_clicked
    self.children.append(InstanceWindow(instance, self.curse))
  File "D:\Program Files (x86)\Minecraft\CustomSoftware\OpenMineMods\GUI\InstanceWindowWrapper.py", line 27, in __init__
    self.curse_mthread = CurseMetaThread(self.curse)
NameError: name 'CurseMetaThread' is not defined
```
OMMv2 crashes upon pressing edit button on preexisting instance
`ui-v2` branch with latest commit `b5d9ca4`

**Comment by Maddremor** [comment]
```
D:\Program Files (x86)\Minecraft\CustomSoftware\OpenMineMods>python OpenMineMods.py
[09/24/17 16:36:53][INFO] Data dir: F:/AppData/Roaming/python
[09/24/17 16:36:53][INFO] Cache dir: C:/Users/Maddremor/AppData/Local/python/cache
['OpenMineMods.py']
Traceback (most recent call last):
  File "D:\Program Files (x86)\Minecraft\CustomSoftware\OpenMineMods\GUI\MainWindowWrapper.py", line 151, in edit_clicked
    self.children.append(InstanceWindow(instance, self.curse))
  File "D:\Program Files (x86)\Minecraft\CustomSoftware\OpenMineMods\GUI\InstanceWindowWrapper.py", line 37, in __init__
    self.pack = self.curse.get_project(self.file.project)
AttributeError: 'bool' object has no attribute 'project'
```
Okay, pulled OMM and CurseMetaDB to `89d458a` and `75a7f12`
Now it's crashing with a new and exciting message.

**Comment by notjuliee** [comment]
Oh wow, that is new and exiting! I'll push a fix for that in a second.

I'm just confused as to where it's pulling the file ID from, if you don't have any mods installed.

[Discord](https://discord.gg/sKyErHT) in case you want faster response times :P
