### ISSUE TITLE
Unable to run from sourcecode (uibuild failed)

### ISSUE THREAD

**Issue by eternaldensity** [joonatoona/OpenMineMods#40]
Checkout worked:
```git clone https://github.com/OpenMineMods/OpenMineMods.git --recursive
Cloning into 'OpenMineMods'...
remote: Counting objects: 1399, done.
remote: Compressing objects: 100% (144/144), done.
remote: Total 1399 (delta 123), reused 132 (delta 59), pack-reused 1196
Receiving objects: 100% (1399/1399), 526.51 KiB | 255.00 KiB/s, done.
Resolving deltas: 100% (908/908), done.
Checking connectivity... done.
Submodule 'CurseMetaDB' (https://github.com/OpenMineMods/CurseMetaDB.git) registered for path 'CurseMetaDB'
Cloning into 'CurseMetaDB'...
remote: Counting objects: 90, done.
remote: Total 90 (delta 0), reused 0 (delta 0), pack-reused 90
Unpacking objects: 100% (90/90), done.
Checking connectivity... done.
Submodule path 'CurseMetaDB': checked out '0f28e589d949bbc629badd5398364bf26e7c3758'
```
Pip install worked because I already installed previously:

```pip3 install --user -r requirements.txt 
Requirement already satisfied: beautifulsoup4 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: pyqt5 in /home/ed/.local/lib/python3.5/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied: fuzzywuzzy in /home/ed/.local/lib/python3.5/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: python-Levenshtein in /home/ed/.local/lib/python3.5/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: sip<4.20,>=4.19.3 in /home/ed/.local/lib/python3.5/site-packages (from pyqt5->-r requirements.txt (line 2))
Requirement already satisfied: setuptools in /home/ed/.local/lib/python3.5/site-packages (from python-Levenshtein->-r requirements.txt (line 5))
```

uibuild failed:
```./uibuild.sh 
Building UI/AnalyticsDialog.ui to GUI/AnalyticsDialog.py
/usr/bin/python: No module named PyQt5.uic
Building UI/ErrorDialog.ui to GUI/ErrorDialog.py
/usr/bin/python: No module named PyQt5.uic
Building UI/ExportDialog.ui to GUI/ExportDialog.py
/usr/bin/python: No module named PyQt5.uic
Building UI/ExportWidget.ui to GUI/ExportWidget.py
/usr/bin/python: No module named PyQt5.uic
Building UI/FileDialog.ui to GUI/FileDialog.py
/usr/bin/python: No module named PyQt5.uic
Building UI/FileWidget.ui to GUI/FileWidget.py
/usr/bin/python: No module named PyQt5.uic
Building UI/InstanceWidget.ui to GUI/InstanceWidget.py
/usr/bin/python: No module named PyQt5.uic
Building UI/InstanceWindow.ui to GUI/InstanceWindow.py
/usr/bin/python: No module named PyQt5.uic
Building UI/MainWindow.ui to GUI/MainWindow.py
/usr/bin/python: No module named PyQt5.uic
Building UI/ModWidget.ui to GUI/ModWidget.py
/usr/bin/python: No module named PyQt5.uic
Building UI/PackWidget.ui to GUI/PackWidget.py
/usr/bin/python: No module named PyQt5.uic
Building UI/ProgressDialog.ui to GUI/ProgressDialog.py
/usr/bin/python: No module named PyQt5.uic
Building UI/SetupDialog.ui to GUI/SetupDialog.py
/usr/bin/python: No module named PyQt5.uic
Building UI/UpdateDialog.ui to GUI/UpdateDialog.py
/usr/bin/python: No module named PyQt5.uic
```
So as would be expected it can't run:

```./OpenMineMods.py 
Traceback (most recent call last):
  File "./OpenMineMods.py", line 5, in <module>
    from Utils.ErrorHandler import handle_exception
  File "/home/ed/Downloads/OpenMineMods/Utils/ErrorHandler.py", line 11, in <module>
    from GUI.ErrorDialogWrapper import ErrorDialog
  File "/home/ed/Downloads/OpenMineMods/GUI/ErrorDialogWrapper.py", line 10, in <module>
    from GUI.ErrorDialog import Ui_ErrorDialog
ImportError: No module named 'GUI.ErrorDialog'
```

Perhaps there's something to install/configure that isn't mentioned in the instructions?

**Comment by notjuliee** [comment]
~~Can you try running `which pyuic5`?~~

Should be fixed in the latest commit, try that.

**Comment by notjuliee** [comment]
That wasn't supposed to close the issue

**Comment by notjuliee** [comment]
So can you pull and try again? It should be fixed now.

**Comment by eternaldensity** [comment]
Yes that fixed it thanks!  It all works now.
