### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by kleshas** [joonatoona/OpenMineMods#55]
ImportError: /usr/lib/libGL.so.1: undefined symbol: __GLXGL_CORE_FUNCTIONS

Was working fine yesterday, gives the above error today.  Rebooted to no effect.
43 packages on archx64 updated since last working.  Lots of "lib*" updates, too many to manually go through and manually downgrade to find the problem package.

**Comment by jambonmcyeah** [comment]
Same issue
I'm using arch too
```
Traceback (most recent call last):
  File "OpenMineMods.py", line 5, in <module>
  File "/usr/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "Utils/ErrorHandler.py", line 3, in <module>
  File "/usr/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "API/CurseAPI.py", line 10, in <module>
  File "/usr/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "API/MultiMC.py", line 9, in <module>
  File "/usr/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "Utils/Utils.py", line 6, in <module>
  File "/usr/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 714, in load_module
ImportError: /usr/lib/libGL.so.1: undefined symbol: __GLXGL_CORE_FUNCTIONS
```

**Comment by kodexyz** [comment]
Can confirm.
I switched to the ui3 branch and it works.
